//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicadbEntities : DbContext
    {
        public medicadbEntities()
            : base("name=medicadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<administracija> administracija { get; set; }
        public DbSet<doktori> doktori { get; set; }
        public DbSet<pacijenti> pacijenti { get; set; }
        public DbSet<termini> termini { get; set; }
        public DbSet<tretmani> tretmani { get; set; }
    }
}
