//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medica
{
    using System;
    using System.Collections.Generic;
    
    public partial class termini
    {
        public int idTermini { get; set; }
        public int Pacijenti_idPacijenti { get; set; }
        public int Doktori_idDoktor { get; set; }
        public Nullable<System.DateTime> datumTermina { get; set; }
        public Nullable<int> satiTermina { get; set; }
        public Nullable<int> ocjenaTermina { get; set; }
        public Nullable<int> soba { get; set; }
        public int Tretmani_idTretmani { get; set; }
    
        public virtual doktori doktori { get; set; }
        public virtual pacijenti pacijenti { get; set; }
        public virtual tretmani tretmani { get; set; }
    }
}
