//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tretmani
    {
        public tretmani()
        {
            this.termini = new HashSet<termini>();
        }
    
        public int idTretmani { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<termini> termini { get; set; }
    }
}
