//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICA
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilo_sta
    {
        public int Uposlenici_idUposlenici { get; set; }
    
        public virtual uposlenici uposlenici { get; set; }
    }
}
